spring:
  datasource:
    url: jdbc:postgresql://ep-falling-surf-33612417.eu-central-1.aws.neon.tech/neondb
    username: Adrian-Rochminski
    password: 2hIXTRzLwyU3
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  session:
    store-type: jdbc

server:
  servlet:
    context-path: /api
    session:
      timeout: 1800

app:
  organizer-role: organizer