spring:
  datasource:
    url: jdbc:postgresql://ep-falling-surf-33612417.eu-central-1.aws.neon.tech/neondb
    username: Adrian-Rochminski
    password: 2hIXTRzLwyU3
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.example.com
    username: eventtu.company@interia.eu
    password: EventTam1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api
    session:
      timeout: 18000

app:
  organizer-role: organizer
  admin-role: admin
